### ISSUE TITLE
Resolve the workflow for task re-assignment

### ISSUE THREAD

**Issue by rochacbruno** [omkarkhatavkar/jirasync#6]
Lets say we have user `A` assigned to `123` issue.
Jirasync runs and creates an assigned Jira task for that user
USer goes and put that task in to the current sprint and start working on it.

Then, for some reason.

User `B` will need to take the issue from user `A`
User `B` goes to redmine/github and self assign the issue.

Currently (in redmine) a new issue will be created for the user `B` because the username is part of the query and also part of the summary.

Question is:

- Is that the right workflow? when user B takes an issue from user A, Jirasync should create a new task on Jira and it is responsability of user `A` to close/complete the existing one.

- Jirasync should take care of re-assignment, updating the `assignee` on every run, re-using the same task and changing its title to use the new assignee name?

**Comment by omkarkhatavkar** [comment]
As we rediscuss this problem we had one solution to not to use username in task title to avoid duplicate tasks getting created. Currently issue, PR_create is a singleton and there will be only one person will be working on that and incase task reassignment required person will be get assigned to that task.

Question is:

Is that the right workflow? when user B takes an issue from user A, Jirasync should create a new task on Jira and it is the responsibility of user A to close/complete the existing one.
**ANS ==> We can add logic in case of re-assignment, at least for GitHub is not exist**  

Jirasync should take care of re-assignment, updating the assignee on every run, re-using the same task and changing its title to use the new assignee name?
****ANS ==> If we do not used the username in the title as discussed earlier above reassignment logic should take care of it ****

**Comment by rochacbruno** [comment]
@omkarkhatavkar moved this conversartion to #9
